language: node_js
node_js:
- '6'
script: npm test
deploy:
  - provider: cloudfoundry
    api: https://api.ng.bluemix.net
    username: markwats@us.ibm.com
    password:
      secure: "xYfoGXlPP26hKwu5GuwcCyE3nlH4AcQz5yf8vOL35tq5at/AiaqjsAXqpm4i3JkughloUYIpEi3Zmg+OPXdudBnmJ6A10HdVxoTzhMz+pY/34woabM+cPbV0G855q1xi4qXImBqG5Ef3vJ3RgnHZqVGTFanMo7orQRjypnP4MF5QUTkLkWUGHqw6z30by3X6K/Z22wJresSDMMqR2fU/QMfzmBScKyriNwhRkNjF97r46sV2GhTQXE8F2LoCCjqvmV9806WHw5eukWOli/CrqbqzrTH6RO/VlUqCA/N5jLecFfvdFXNTnCn/5wgp/cx3BYI8ugA0ZpDm2JDZnoKNwc843QmcqZn955T2GhmxnHvpCh60g+4DmWiHploxQj4uvo3JR4gU53LK470DwLZz7XhzI4CpHcGTiBHQ17oWtXpWlH49xE1ZYaknQ6rKQ20f7U0nIjrHpsGutlpqsBamLrGu+vG1VbSP+fRNAamALKI/uRzhnf9utOKz8mJMwpJ+JVbUBRIHUwREgWkqykDomfET0r5QfIId/YN0HmpxRRSh6O8lsvlj6+XhpNkkAnOrwaDgaHgJoTBfdLn4dGr5Mk8xKZP6/mEekPQ69YhKo8NYTYcE1oc6j1FjgM49AgzTY1JC9jzDR3IVl+6h+czUuaHy50OklrpCEYp4Re5skpY="
    organization: bradley.holt@us.ibm.com
    space: hoodie-partnership
    manifest: manifest.staging.yml
    on:
      repo: neighbourhoodie/voice-of-interconnect
      branch: master
  - provider: cloudfoundry
    api: https://api.ng.bluemix.net
    username: markwats@us.ibm.com
    password:
      secure: "xYfoGXlPP26hKwu5GuwcCyE3nlH4AcQz5yf8vOL35tq5at/AiaqjsAXqpm4i3JkughloUYIpEi3Zmg+OPXdudBnmJ6A10HdVxoTzhMz+pY/34woabM+cPbV0G855q1xi4qXImBqG5Ef3vJ3RgnHZqVGTFanMo7orQRjypnP4MF5QUTkLkWUGHqw6z30by3X6K/Z22wJresSDMMqR2fU/QMfzmBScKyriNwhRkNjF97r46sV2GhTQXE8F2LoCCjqvmV9806WHw5eukWOli/CrqbqzrTH6RO/VlUqCA/N5jLecFfvdFXNTnCn/5wgp/cx3BYI8ugA0ZpDm2JDZnoKNwc843QmcqZn955T2GhmxnHvpCh60g+4DmWiHploxQj4uvo3JR4gU53LK470DwLZz7XhzI4CpHcGTiBHQ17oWtXpWlH49xE1ZYaknQ6rKQ20f7U0nIjrHpsGutlpqsBamLrGu+vG1VbSP+fRNAamALKI/uRzhnf9utOKz8mJMwpJ+JVbUBRIHUwREgWkqykDomfET0r5QfIId/YN0HmpxRRSh6O8lsvlj6+XhpNkkAnOrwaDgaHgJoTBfdLn4dGr5Mk8xKZP6/mEekPQ69YhKo8NYTYcE1oc6j1FjgM49AgzTY1JC9jzDR3IVl+6h+czUuaHy50OklrpCEYp4Re5skpY="
    organization: bradley.holt@us.ibm.com
    space: hoodie-partnership
    manifest: manifest.prod.yml
    on:
      repo: neighbourhoodie/voice-of-interconnect
      branch: live