language: node_js
node_js:
- '6'
script: npm test
deploy:
  - provider: cloudfoundry
    api: https://api.ng.bluemix.net
    username: markwats@us.ibm.com
    password:
      secure: "Ubdhg44i4GzmOfP5Ag0MJ1WPiWhbUl5RV8kaHgIcEnzIousSmjNOQ0KCjqFBYBIL/ARnLO+5MdROviKSKxugplTab8Mox1sidgnPdmFDfVKfsS1YIB8a5xJn25/QNr5RRIVv+VvJ4KQctbijnX1mH45CObcLB4rNOzVO7y26mv8R+5YYrSrHPgLIAo7/hLjI8qGzDX7t1wXayqDMsjLmt4yC2t/6WY4QYCbaGF9JFWRWJ5n0ios9Pw3OF9FcEof9yveTQhvs1WvLyRDcNWvLSKFsgGWZ3E8Bqlp0HNAoBdhjXPwj1YarVDRnyZvC5/LwqcI1YKKJgWpjBaJF0SGkRMAi9dc7eyLN8KnYydguS6eizeki6ttDCzRS7sjW5DmXGjTS0k3daSsGKjKSIZ+cfk9YqdYSEbrEyuWAqCkJoV9n83itsvpjFexNsvpq3CJnS8PQ7nmfrW2oic32YlqDTZ6qHnVRIEUcWpbmvvPKE64uSHR4A0c24vRjEPSeFyzp+0iblQHeV7TW0I9yVE6olxVETxRqxOfJJAr17uFAbb6na82LrQzZ7shW1F/oE4j4/ZdXQKcZa8zUhhIQKvF7TdJFUbzpuaQXQSWRYZ4XREAWlJe/fizbeEH+0hhxo0BUbLpHb/e4HTOulO+J54YFNMgBuBg7E6cUPXBTlVNat2g="
    organization: bradley.holt@us.ibm.com
    space: hoodie-partnership
    manifest: manifest.staging.yml
    on:
      repo: neighbourhoodie/voice-of-interconnect
      branch: master
  - provider: cloudfoundry
    api: https://api.ng.bluemix.net
    username: markwats@us.ibm.com
    password:
      secure: "Ubdhg44i4GzmOfP5Ag0MJ1WPiWhbUl5RV8kaHgIcEnzIousSmjNOQ0KCjqFBYBIL/ARnLO+5MdROviKSKxugplTab8Mox1sidgnPdmFDfVKfsS1YIB8a5xJn25/QNr5RRIVv+VvJ4KQctbijnX1mH45CObcLB4rNOzVO7y26mv8R+5YYrSrHPgLIAo7/hLjI8qGzDX7t1wXayqDMsjLmt4yC2t/6WY4QYCbaGF9JFWRWJ5n0ios9Pw3OF9FcEof9yveTQhvs1WvLyRDcNWvLSKFsgGWZ3E8Bqlp0HNAoBdhjXPwj1YarVDRnyZvC5/LwqcI1YKKJgWpjBaJF0SGkRMAi9dc7eyLN8KnYydguS6eizeki6ttDCzRS7sjW5DmXGjTS0k3daSsGKjKSIZ+cfk9YqdYSEbrEyuWAqCkJoV9n83itsvpjFexNsvpq3CJnS8PQ7nmfrW2oic32YlqDTZ6qHnVRIEUcWpbmvvPKE64uSHR4A0c24vRjEPSeFyzp+0iblQHeV7TW0I9yVE6olxVETxRqxOfJJAr17uFAbb6na82LrQzZ7shW1F/oE4j4/ZdXQKcZa8zUhhIQKvF7TdJFUbzpuaQXQSWRYZ4XREAWlJe/fizbeEH+0hhxo0BUbLpHb/e4HTOulO+J54YFNMgBuBg7E6cUPXBTlVNat2g="
    organization: bradley.holt@us.ibm.com
    space: hoodie-partnership
    manifest: manifest.prod.yml
    on:
      repo: neighbourhoodie/voice-of-interconnect
      branch: live