---
stages:
- name: Build Stage
  inputs:
  - type: git
    branch: deploy-to-bluemix
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
    build_type: npm
    script: |-
      #!/bin/bash
      export PATH=/opt/IBM/node-v6.7.0/bin:$PATH
      npm install
      npm run build
      rm .cfignore
